<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Date_fa fa-pencil</name>
   <tag></tag>
   <elementGuidId>97b9b939-0726-4155-bdc4-adff5367bdbd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[3]/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-pencil</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js ng-scope&quot;]/body[1]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;ng-scope&quot;]/div[@class=&quot;conference-body ng-scope&quot;]/main[1]/div[@class=&quot;ng-scope&quot;]/ui-view[@class=&quot;ng-scope&quot;]/div[@class=&quot;conference-details-overview ng-scope&quot;]/div[1]/div[@class=&quot;table-responsive table-responsive-right-border&quot;]/table[@class=&quot;table&quot;]/tbody[1]/tr[1]/td[@class=&quot;ng-scope&quot;]/div[@class=&quot;default-icon-circle ng-scope&quot;]/i[@class=&quot;fa fa-pencil&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/i</value>
   </webElementXpaths>
</WebElementEntity>
