<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Puppy roof_fr-fic fr-dib fr-draggable</name>
   <tag></tag>
   <elementGuidId>1f48076e-d8ee-4ba5-ae85-1ea2804a87ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.fr-fic.fr-dib.fr-draggable</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='overview']/div/div/p/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>blob:https://rc.app.expopass.com/6a050c27-8391-4cf4-bf5c-1f7a807d9dba</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fr-fic fr-dib fr-draggable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;overview&quot;)/div[@class=&quot;welcome-text-wrapper&quot;]/div[@class=&quot;event-welcome-text froala ng-star-inserted&quot;]/p[1]/img[@class=&quot;fr-fic fr-dib fr-draggable&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='overview']/div/div/p/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'blob:https://rc.app.expopass.com/6a050c27-8391-4cf4-bf5c-1f7a807d9dba')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p/img</value>
   </webElementXpaths>
</WebElementEntity>
